### ISSUE TITLE
Auto-population of dropdown fields in settings 

### ISSUE THREAD

**Issue by mmaist** [zeno-ml/zeno-hub#644] opened 2024-01-11 23:21 UTC
Collaborators and Organizations dropdown fields auto-populate in the settings pop-up of a project. These should be scoped to a given organization rather than what seems to be all of them.

![image](https://github.com/zeno-ml/zeno-hub/assets/10469829/71899af4-85a3-4436-b8d5-c91964727c10)

System:
MacOS

Chrome

**Comment by cabreraalex** [comment] 2024-01-11 23:47
Thanks for finding this, definitely a bug! Should be just the orgs you are an admin on. Will take a look soon

**Comment by Sparkier** [comment] 2024-04-15 16:10
This is by design rather than by accident. We've had multiple occasions where we needed to be able to share projects with organizations we were not members of. Closing for now.

**Closed by Sparkier** 2024-04-15 16:10 UTC
Labels: bug
